"""Build the module map an issue triage needs, from a repository's git history.

An issue carries no diff, so Jev cannot be asked what a fix will cost. It can be
asked where the fix will land, and this script measures what landing there has
cost before. The output is `modules.yml`: one entry per destination, carrying the
paths it covers and the size of a typical change that touches it.

Two halves of that file come from different places, and the split matters:

  measured   cost_median_files, cost_p75_files, variance_ratio, obligations
             computed here from git log and the workflow path filters

  judgement  description, globs, risk
             written by a person or an agent who has read the code, because git
             history says what a change to auth has cost and never says what it
             would cost to get wrong, and a directory name is not something an
             issue body can decide

So a cold run proposes clusters and leaves the judgement fields blank. A refresh
recomputes the measured fields and preserves the judgement ones.

This script needs a git checkout and no API keys.

Usage:
    uv run build_module_map.py --repo-path ~/repos/my-repo
    uv run build_module_map.py --repo-path . --refresh
    uv run build_module_map.py --repo-path . --check
"""

import argparse
import collections
import logging
import pathlib
import re
import statistics
import subprocess
import sys

import yaml

# Configure logging with basicConfig
logging.basicConfig(
    level=logging.INFO,  # Set the log level to INFO
    # Define log message format
    format="%(asctime)s,p%(process)s,{%(filename)s:%(lineno)d},%(levelname)s,%(message)s",
)
logger = logging.getLogger(__name__)

DEFAULT_OUT: str = "modules.yml"

# How far back to measure. Long enough to cover a few release cycles, short
# enough that a tree reorganised last year does not drag the medians.
DEFAULT_SINCE_DAYS: int = 240

# A top-level directory holding more than this many tracked files gets proposed
# as several destinations, one per subdirectory. Below it, one destination covers
# the whole directory. Twelve or so destinations is the useful range: finer
# prediction helps the cost lookup and hurts the accuracy, because the issue body
# has to be able to decide it.
SPLIT_THRESHOLD: int = 120

# Directory names proposed as obligations rather than destinations. An
# obligation comes along with a change wherever it lands, so asking Jev whether
# an issue "touches tests" wastes a question on something the destination
# already implies.
#
# This is a name list and not a measurement, because git history cannot tell the
# two apart. Commit share says tests touches 36% of commits and registry 33%,
# which would classify the core package as an obligation. The solo-change rate
# is worse: registry sits at 10% and auth_server at 8%, both below tests at 15%,
# because registry cannot change without its tests and the pairing looks the
# same from either side. The script records both figures as evidence and leaves
# the call to whoever curates the file.
DEFAULT_OBLIGATION_NAMES: frozenset[str] = frozenset(
    {"tests", "test", "docs", "doc", "spec", "specs", "release-notes", "fixtures"}
)

# Split a directory only when at least this many of its subdirectories are
# substantial. A 249-file frontend whose files all sit under src/ gains nothing
# from splitting.
MIN_SUBDIRS_TO_SPLIT: int = 2
MIN_SUBDIR_FILES: int = 25

# Destinations below this many commits are folded out. A directory nobody has
# touched in the window carries no measurement worth keeping.
MIN_COMMITS: int = 8

# The most destinations to propose. Finer prediction helps the cost lookup and
# hurts the accuracy, because an issue body has to be able to decide between
# them. The coverage check forces the folded paths to be given a home by hand.
MAX_DESTINATIONS: int = 14

# Files that say nothing about where work lands.
IGNORED_SUFFIXES: tuple[str, ...] = (".lock", ".sum", ".tgz", ".png", ".svg", ".ico")

# Workflow path filters name obligations. This pulls the `paths:` lists out of
# every workflow, which is a machine-readable map from a path to what it owes.
WORKFLOW_GLOB: str = ".github/workflows/*.y*ml"
PATHS_BLOCK: re.Pattern[str] = re.compile(r"paths:\s*\n((?:\s*-\s*\S+\n)+)")
PATH_ENTRY: re.Pattern[str] = re.compile(r"-\s*['\"]?([^'\"\s]+)['\"]?")

# Fields a refresh recomputes. Everything else in an existing file survives.
MEASURED_FIELDS: tuple[str, ...] = (
    "cost_median_files",
    "cost_p75_files",
    "variance_ratio",
    "commits_touching",
)

HEADER: str = """\
# Module map: where an issue's fix lands, and what landing there has cost.
#
# Generated by build_module_map.py from {commits} commits over {days} days.
# Regenerate the measured fields with --refresh, which preserves everything a
# person wrote. Check coverage with --check.
#
# measured   cost_median_files, cost_p75_files, variance_ratio, obligations
# judgement  description, globs, risk
#
# `description` is the only text Jev reads, so write it so an issue body can
# decide it. "Where registry records are stored and read back" is decidable.
# "registry/repositories" is not.
#
# `risk` is how bad a wrong change here would be, from 0 to 1, and it drives the
# security lane. Git history cannot measure it.
#
# Every tracked file must match one destination glob or one obligation glob.
# --check enforces that, because an unmapped path gets no cost lookup and fails
# quietly.
"""


def _run_git(
    repo: pathlib.Path,
    args: list[str],
) -> str:
    """Run a git command in the repository and return its stdout.

    Args:
        repo: Path to the git checkout.
        args: Git arguments, without the leading "git".

    Returns:
        The command's standard output.

    Raises:
        SystemExit: If the directory is not a git checkout.
    """
    try:
        return subprocess.run(  # nosec B603 B607 - hardcoded command, path from the caller
            ["git", "-C", str(repo), *args],
            capture_output=True,
            text=True,
            check=True,
            timeout=120,
        ).stdout
    except subprocess.CalledProcessError as e:
        raise SystemExit(f"git {' '.join(args)} failed in {repo}: {e.stderr.strip()}") from e
    except FileNotFoundError as e:
        raise SystemExit("git is not on PATH") from e


def _tracked_files(repo: pathlib.Path) -> list[str]:
    """List every tracked file, dropping the ones that say nothing about work."""
    files = [f for f in _run_git(repo, ["ls-files"]).splitlines() if f]
    return [f for f in files if not f.endswith(IGNORED_SUFFIXES)]


def _propose_clusters(
    files: list[str],
    commits: list[list[str]],
) -> tuple[dict[str, list[str]], list[str]]:
    """Group tracked paths into candidate destinations and obligations.

    Obligations come from DEFAULT_OBLIGATION_NAMES, not from a measurement, and
    they are set aside before anything splits. Splitting first would hide them:
    `tests/` touches 36% of commits, but `tests/fixtures` alone touches few
    enough to look like a destination.

    Only the remaining directories split, and only when several of their
    subdirectories are substantial enough to be separate areas.

    Args:
        files: Tracked file paths.
        commits: Each commit as its list of changed paths.

    Returns:
        A tuple of (cluster name mapped to path prefixes, obligation names).
    """
    by_top: dict[str, list[str]] = collections.defaultdict(list)
    for f in files:
        by_top[f.split("/")[0] if "/" in f else "(root)"].append(f)

    obligations = sorted(n for n in by_top if n in DEFAULT_OBLIGATION_NAMES)
    logger.info(f"obligations by name: {', '.join(obligations) or 'none'}")

    clusters: dict[str, list[str]] = {}
    for top, members in by_top.items():
        if top in obligations:
            continue
        if top == "(root)":
            clusters[top] = ["*"]
            continue
        subs = _substantial_subdirs(top, members)
        if len(subs) < MIN_SUBDIRS_TO_SPLIT:
            clusters[top] = [top]
            continue
        for name in subs:
            clusters[name] = [name]
        logger.debug(f"split {top} into {len(subs)} clusters")

    logger.info(f"proposed {len(clusters)} clusters from {len(files)} tracked files")
    return clusters, obligations


def _substantial_subdirs(
    top: str,
    members: list[str],
) -> list[str]:
    """Return the subdirectories of `top` big enough to stand as destinations."""
    subs: dict[str, int] = collections.Counter()
    for f in members:
        parts = f.split("/")
        if len(parts) > 2:
            subs[f"{top}/{parts[1]}"] += 1
    return sorted(n for n, c in subs.items() if c >= MIN_SUBDIR_FILES)


def _cluster_of(
    path: str,
    prefixes: dict[str, list[str]],
) -> str | None:
    """Return the cluster a path belongs to, longest prefix winning."""
    best, best_len = None, -1
    for name, pres in prefixes.items():
        for pre in pres:
            if pre == "*":
                if "/" not in path and best_len < 0:
                    best, best_len = name, 0
            elif (path == pre or path.startswith(pre + "/")) and len(pre) > best_len:
                best, best_len = name, len(pre)
    return best


def _read_commits(
    repo: pathlib.Path,
    since_days: int,
) -> list[list[str]]:
    """Read each commit in the window as its list of changed paths."""
    log = _run_git(
        repo,
        [
            "log",
            f"--since={since_days} days ago",
            "--no-merges",
            "--pretty=format:@@%H",
            "--name-only",
        ],
    )
    commits: list[list[str]] = []
    current: list[str] | None = None
    for line in log.splitlines():
        if line.startswith("@@"):
            if current:
                commits.append(current)
            current = []
        elif line.strip() and current is not None:
            current.append(line.strip())
    if current:
        commits.append(current)
    logger.info(f"read {len(commits)} commits over {since_days} days")
    return commits


def _measure(
    commits: list[list[str]],
    clusters: dict[str, list[str]],
) -> dict[str, dict]:
    """Measure what a change costs when it touches each cluster.

    The size recorded is the size of the whole commit, not the part inside the
    cluster, because that is the question a triage asks: a change landing in
    `charts` drags terraform along, and the median already counts it.

    Args:
        commits: Each commit as its list of changed paths.
        clusters: Cluster name mapped to its path prefixes.

    Returns:
        Cluster name mapped to its measurements and co-change counts.
    """
    files_when: dict[str, list[int]] = collections.defaultdict(list)
    mods_when: dict[str, list[int]] = collections.defaultdict(list)
    cooccur: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)

    for paths in commits:
        touched = {c for c in (_cluster_of(p, clusters) for p in paths) if c}
        for name in touched:
            files_when[name].append(len(paths))
            mods_when[name].append(len(touched))
            for other in touched - {name}:
                cooccur[name][other] += 1

    out: dict[str, dict] = {}
    for name in clusters:
        sizes = sorted(files_when.get(name, []))
        if not sizes:
            continue
        median = statistics.median(sizes)
        p75 = sizes[int(len(sizes) * 0.75)]
        out[name] = {
            "cost_median_files": int(median),
            "cost_p75_files": int(p75),
            "variance_ratio": round(p75 / median, 2) if median else 1.0,
            "commits_touching": len(sizes),
            "median_modules": int(statistics.median(mods_when[name])),
            "co_change": [n for n, _ in cooccur[name].most_common(3)],
        }
    return out


def _select_destinations(measured: dict[str, dict]) -> list[str]:
    """Pick the destinations worth predicting, busiest first.

    A directory nobody has touched in the window carries no measurement worth
    keeping, and a list longer than MAX_DESTINATIONS asks Jev to make a
    distinction an issue body cannot support. Both get folded out, and the
    coverage check then forces whoever curates the file to give the folded paths
    a home.

    Returns:
        Destination names, sorted alphabetically.
    """
    busy = [
        (name, m["commits_touching"])
        for name, m in measured.items()
        if m["commits_touching"] >= MIN_COMMITS
    ]
    dropped = len(measured) - len(busy)
    if dropped:
        logger.debug(f"{dropped} cluster(s) below {MIN_COMMITS} commits, folded out")

    busy.sort(key=lambda x: -x[1])
    if len(busy) > MAX_DESTINATIONS:
        folded = [n for n, _ in busy[MAX_DESTINATIONS:]]
        logger.info(
            f"keeping the {MAX_DESTINATIONS} busiest, folding {len(folded)}: "
            f"{', '.join(folded[:8])}{' ...' if len(folded) > 8 else ''}"
        )
        busy = busy[:MAX_DESTINATIONS]

    logger.info(f"{len(busy)} destinations proposed")
    return sorted(n for n, _ in busy)


def _workflow_triggers(repo: pathlib.Path) -> dict[str, list[str]]:
    """Map a workflow name to the path globs that trigger it.

    Every workflow's `on: paths:` filter is a machine-readable statement of what
    a change to those paths owes, which beats a hand-written table that nobody
    updates.
    """
    triggers: dict[str, list[str]] = {}
    for wf in sorted(repo.glob(WORKFLOW_GLOB)):
        text = wf.read_text(encoding="utf-8", errors="replace")
        globs: list[str] = []
        for block in PATHS_BLOCK.findall(text):
            globs.extend(PATH_ENTRY.findall(block))
        if globs:
            triggers[wf.name] = sorted(set(globs))
    logger.info(f"read path filters from {len(triggers)} workflows")
    return triggers


def _check_coverage(
    files: list[str],
    spec: dict,
) -> list[str]:
    """Return tracked paths matching no destination or obligation glob.

    An unmapped path gets no cost lookup and fails quietly, which is the worst
    way for this to break, so the caller turns a non-empty result into an error.
    """
    prefixes: dict[str, list[str]] = {}
    for name, entry in spec.get("destinations", {}).items():
        prefixes[name] = entry.get("globs") or []
    prefixes["(obligations)"] = spec.get("obligations", {}).get("globs", [])
    stripped = {k: [g.rstrip("/*").rstrip("/") or "*" for g in v] for k, v in prefixes.items()}
    return [f for f in files if _cluster_of(f, stripped) is None]


def _build_spec(
    repo: pathlib.Path,
    since_days: int,
    existing: dict | None,
) -> tuple[dict, int]:
    """Assemble the module map, preserving any judgement fields already written."""
    files = _tracked_files(repo)
    commits = _read_commits(repo, since_days)

    if existing and existing.get("destinations"):
        clusters = {
            name: entry.get("globs") or [name] for name, entry in existing["destinations"].items()
        }
        obligation_globs = existing.get("obligations", {}).get("globs", [])
        clusters["(obligations)"] = obligation_globs
        stripped = {k: [g.rstrip("/*").rstrip("/") or "*" for g in v] for k, v in clusters.items()}
        measured = _measure(commits, stripped)
        dest_names = sorted(existing["destinations"])
        oblig_names = ["(obligations)"]
    else:
        clusters, oblig_names = _propose_clusters(files, commits)
        measured = _measure(commits, clusters)
        dest_names = _select_destinations(measured)

    destinations: dict[str, dict] = {}
    for name in dest_names:
        prior = (existing or {}).get("destinations", {}).get(name, {})
        m = measured.get(name, {})
        destinations[name] = {
            "description": prior.get("description", ""),
            "globs": prior.get("globs") or clusters.get(name, [name]),
            "risk": prior.get("risk", None),
            **{f: m.get(f) for f in MEASURED_FIELDS},
            "median_modules": m.get("median_modules"),
            "co_change": m.get("co_change", []),
        }

    spec = {
        "repo": existing.get("repo") if existing else None,
        "generated_from_commits": len(commits),
        "window_days": since_days,
        "destinations": destinations,
        "obligations": {
            "globs": (existing or {}).get("obligations", {}).get("globs")
            or [f"{n}/**" for n in oblig_names if n != "(obligations)"],
            "workflow_triggers": _workflow_triggers(repo),
        },
        "conventions": (existing or {}).get(
            "conventions",
            {
                "skip_labels": ["awaiting-response", "wontfix", "duplicate", "invalid"],
                "parking_milestone_pattern": "parking",
            },
        ),
    }
    return spec, len(commits)


def _write_spec(
    spec: dict,
    out: pathlib.Path,
    commits: int,
    days: int,
) -> None:
    """Write the module map with its header comment."""
    body = yaml.dump(spec, sort_keys=False, default_flow_style=False, width=100)
    out.write_text(HEADER.format(commits=commits, days=days) + "\n" + body, encoding="utf-8")
    logger.info(f"wrote {out}")


def _report_blanks(spec: dict) -> int:
    """Log the judgement fields still waiting on a person, and count them."""
    blank = [
        name
        for name, e in spec["destinations"].items()
        if not e.get("description") or e.get("risk") is None
    ]
    if blank:
        logger.warning(
            f"{len(blank)} destination(s) need a description and a risk before triage: "
            f"{', '.join(blank)}"
        )
    return len(blank)


def check(
    repo: pathlib.Path,
    out: pathlib.Path,
) -> int:
    """Verify an existing module map covers every tracked file.

    Returns:
        Process exit code: 0 when every path maps, 1 otherwise.
    """
    if not out.is_file():
        logger.error(f"{out} does not exist, so there is nothing to check")
        return 1
    spec = yaml.safe_load(out.read_text(encoding="utf-8"))
    unmapped = _check_coverage(_tracked_files(repo), spec)
    if not unmapped:
        logger.info(f"{out}: every tracked file maps to a destination or an obligation")
        return 0
    by_dir = collections.Counter(
        "/".join(f.split("/")[:2]) if "/" in f else "(root)" for f in unmapped
    )
    logger.error(f"{len(unmapped)} tracked file(s) map to nothing:")
    for d, c in by_dir.most_common(20):
        logger.error(f"  {c:>4}  {d}")
    logger.error("add a glob for each, or list it under obligations, then re-run --check")
    return 1


def build(
    repo: pathlib.Path,
    out: pathlib.Path,
    since_days: int,
    refresh: bool,
) -> int:
    """Generate or refresh the module map.

    Returns:
        Process exit code.
    """
    existing = None
    if refresh:
        if not out.is_file():
            logger.error(f"--refresh needs an existing {out}")
            return 1
        existing = yaml.safe_load(out.read_text(encoding="utf-8"))
        logger.info(f"refreshing the measured fields of {out}, keeping the written ones")

    spec, commits = _build_spec(repo, since_days, existing)
    _write_spec(spec, out, commits, since_days)

    unmapped = _check_coverage(_tracked_files(repo), spec)
    if unmapped:
        logger.warning(
            f"{len(unmapped)} tracked file(s) map to nothing yet. "
            f"Run --check for the list once you have edited the globs."
        )
    _report_blanks(spec)
    logger.info(
        f"{len(spec['destinations'])} destinations. "
        f"Next: write each description and risk, then run --check."
    )
    return 0


def main() -> None:
    """Parse arguments and dispatch."""
    parser = argparse.ArgumentParser(
        description="Build the module map an issue triage needs, from git history.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
    # Propose destinations and measure what each has cost
    uv run build_module_map.py --repo-path ~/repos/my-repo

    # Recompute the measured fields, keeping every description and risk
    uv run build_module_map.py --repo-path ~/repos/my-repo --refresh

    # Fail when a tracked file maps to no destination and no obligation
    uv run build_module_map.py --repo-path ~/repos/my-repo --check
""",
    )
    parser.add_argument(
        "--repo-path",
        default=".",
        help="Path to the git checkout to measure (default: the current directory)",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_OUT,
        help=f"Where to write the module map (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--since-days",
        type=int,
        default=DEFAULT_SINCE_DAYS,
        help=f"How far back to measure (default: {DEFAULT_SINCE_DAYS})",
    )
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="Recompute the measured fields of an existing map, preserving the written ones",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify an existing map covers every tracked file, and exit non-zero if not",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Raise the log level to DEBUG",
    )
    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    repo = pathlib.Path(args.repo_path).expanduser().resolve()
    out = pathlib.Path(args.out)
    logger.info(f"repo {repo}, out {out}")

    if args.check:
        sys.exit(check(repo, out))
    sys.exit(build(repo, out, args.since_days, args.refresh))


if __name__ == "__main__":
    main()
